////
Copyright (c) 2020 Krystian Stasiowski (sdkrystian@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

= 初始化列表
初始化列表可用于构造或赋值一个&lt;<ref_value>&gt;：</ref_value>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_1,indent=0]
----

简单的初始化列表会生成一个&lt;<ref_array>&gt;：</ref_array>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_2,indent=0]
----

初始化列表可以嵌套。这里我们构造一个数组作为数组的元素：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_3,indent=0]
----

当一个包含两个元素的初始化列表嵌套在一个封闭的初始化列表中时，它代表的是&lt;<ref_array>&gt;还是&lt;<ref_object>&gt;是不明确的：</ref_object></ref_array>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_4,indent=0]
----

在这种情况下，如果每个元素都由一个字符串后跟一个单一值组成，则封闭的初始化列表会被解释为&lt;<ref_object>&gt;。否则，它会被解释为&lt;<ref_array>&gt;。</ref_array></ref_object>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_5,indent=0]
----

要手动消除歧义，请使用显式构造函数：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_6,indent=0]
----

初始化列表可用于明确地构造或赋值&lt;<ref_object>&gt;或&lt;<ref_array>&gt;：</ref_array></ref_object>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_7,indent=0]
----

类似地，用于&lt;<ref_object>&gt;的初始化列表总是被解释为&lt;<ref_object>&gt;。在这种情况下，初始化列表必须是键值对的列表。例如，以下代码将无法编译，因为`1`无法转换为字符串：</ref_object></ref_object>

[source]
----
object jo = { { 1, 0.39 }, { "venus", 0.72 }, { "earth", 1 } };
----

当初始化此类实体时，将初始化列表解释为&lt;<ref_object>&gt;或&lt;<ref_array>&gt;的要求仅适用于最外层的初始化列表；后续嵌套元素将遵循通常的歧义解决规则。</ref_array></ref_object>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_8,indent=0]
----

作为右值的元素将在初始化时被移动：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_init_list_9,indent=0]
----

[WARNING]
====
不要创建类型为{std_initializer_list}的变量。这可能导致临时对象在初始化列表使用前被销毁。
====

在所有情况下，由初始化列表构造的&lt;<ref_object>&gt;、&lt;<ref_array>&gt;或&lt;<ref_value>&gt;所拥有的&lt;<ref_storage_ptr>&gt;将被递归地传播到每个元素。</ref_storage_ptr></ref_value></ref_array></ref_object>
