////
Copyright (c) 2020 Krystian Stasiowski (sdkrystian@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

[#dom_numbers]
= 数字
JSON数字使用`std::int64_t`、`std::uint64_t`和`double`表示。当&lt;<ref_value>&gt;从无符号整数构造时，其&lt;<ref_kind>&gt;将为`kind::uint64`。同样，从有符号整数构造的&lt;<ref_value>&gt;将具有`kind::int64`，若从浮点类型构造则为`kind::double_`：</ref_value></ref_kind></ref_value>

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_1,indent=0]
----

访问&lt;<ref_value>&gt;内包含的数字时，所用函数必须与值的&lt;<ref_kind>&gt;完全匹配；不会执行任何转换。例如，在包含`std::uint64_t`的&lt;<ref_value>&gt;上调用`as_double`将抛出异常。类似地，函数`if_double`将返回`nullptr`，而调用`get_double`将导致未定义行为：</ref_value></ref_kind></ref_value>

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_2,indent=0]
----

若已知&lt;<ref_value>&gt;包含数字但不确定其&lt;<ref_kind>&gt;，可使用`value::to_number`将该&lt;<ref_value>&gt;转换为算术类型：</ref_value></ref_kind></ref_value>

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_3,indent=0]
----

若&lt;<ref_value>&gt;不包含数字，或当转换目标为整数类型`T`且数字无法被`T`精确表示时，转换将失败。否则，结果是通过`static_cast`将数字转换为`T`：</ref_value>

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_4,indent=0]
----

在无法使用异常的场合，可改用接受{ref_error_code}的`value::to_number`重载，其语义与抛出异常版本完全相同：

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_5,indent=0]
----

解析JSON文档时，用于表示数字的类型未显式指定，必须根据其值确定。通常，解析器会选择能准确存储文档中数字值的最佳类型。无法用`std::uint64_t`和`std::int64_t`表示的整数（即无小数或指数的数字）将表示为`double`以保留其数值：

[source]
----
include::../../../test/doc_using_numbers.cpp[tag=doc_using_numbers_6,indent=0]
----

更正式地，若数字：

* 包含小数点，或
* 包含指数，或
* 为负数且其值小于`INT64_MIN`，或
* 为正数且其值大于`UINT64_MAX`，

则其类型为`double`。否则，若数字为正数且其值大于`INT64_MAX`，则其类型为`std::uint64_t`。其余所有数字均解析为`std::int64_t`。
