////
Copyright (c) 2019 Vinnie Falco (vinnie.falco@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

[#dom_object]
= `object`
&lt;<ref_value>&gt; 将 &lt;<ref_object>&gt; 的实例存储为 JSON 对象的底层表示。&lt;<ref_object>&gt; 类型的实例是保存键值对的关联容器，其中键为 &lt;<ref_string_view>&gt;，映射类型为 &lt;<ref_value>&gt;。这些容器基于标准映射建模，具有以下特性：</ref_value></ref_string_view></ref_object></ref_object></ref_value>

* 元素作为 &lt;<ref_key_value_pair>&gt; 的实例连续存储。</ref_key_value_pair>

* 迭代器为普通指针，在插入和删除操作时可能失效。

* 只要不发生删除操作，插入顺序即被保留。

* 所有插入的值将使用与容器本身相同的 {ref_memory_resource}。

可使用 &lt;&gt; 构造空对象而不产生任何内存分配。也可显式指定 &lt;<ref_storage_ptr>&gt;：</ref_storage_ptr>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_objects_1,indent=0]
----

由键值对组成的初始化列表可用于构造含初始内容的对象。这些构造函数可能分配内存并抛出异常：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_objects_2,indent=0]
----

或者，可在构造后插入元素：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_objects_3,indent=0]
----

与 `std` 对应容器类似，可通过 &lt;<ref_object_at>&gt; 使用边界检查直接按键访问元素，或通过 &lt;<ref_object_operator_lb_rb>&gt; 进行无边界检查访问（若键不存在则创建空元素）：</ref_object_operator_lb_rb></ref_object_at>

[source]
----
include::../../../test/snippets.cpp[tag=snippet_objects_4,indent=0]
----

容器内部通过键计算哈希表，使得查找复杂度平均为常数时间。

[WARNING]
====
与传统的基于节点的容器（如 `std::set`）不同，插入和擦除操作不保证引用稳定性或迭代器稳定性。

例如：

[source]
----
include::../../../test/snippets.cpp[tag=snippet_objects_5,indent=0]
----

向 `obj` 添加新值后继续使用 `arr` 将导致未定义行为。
====

完整成员函数及嵌套类型列表请参阅 &lt;<ref_object>&gt; 的参考页。</ref_object>

与 `std::pair` 类似，&lt;<ref_key_value_pair>&gt; 类型可用于 {cpp}17 的结构化绑定。为此专门提供了 `std::tuple_size`、`std::tuple_element` 的特化及 &lt;<ref_get>&gt; 的重载。</ref_get></ref_key_value_pair>

== 格式化输出

当 &lt;<ref_object>&gt; 被格式化输出到 {std_ostream} 时，结果将是有效的 JSON。即根据 JSON 规范，对象将以花括号和逗号分隔的键/值对列表形式输出。</ref_object>
