////
Copyright (c) 2019 Vinnie Falco (vinnie.falco@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

[#comparison, pagelevels=1,toclevels=1]
= 与其他库的比较

:icon_good: pass:q[[.green]##&#10004##]
:icon_bad:  pass:q[[.red]##&#10008##]

存在许多C++ JSON库，但为了比较的目的，有三个特别值得注意：https://rapidjson.org/[RapidJSON]、https://nlohmann.github.io/json/[JSON for Modern {cpp}]（本文中称为nlohmann的JSON，或nlohmann）以及https://github.com/lemire/simdjson[SIMD JSON]。

== 与nlohmann JSON的比较

值类型：https://github.com/nlohmann/json/blob/00cb98a3d170161711ab912ae6acefba31f29f75/include/nlohmann/json.hpp#L165[`nlohmann::basic_json`]

[source]
----
template&lt;
  template<typename, typename,="" typename...=""> class ObjectType,
  template<typename, typename...=""> class ArrayType,
  class StringType,
  class BooleanType,
  class NumberIntegerType,
  class NumberUnsignedType,
  class NumberFloatType,
  template<typename> class AllocatorType,
  template<typename, typename="void"> class JSONSerializer
  &gt;
class basic_json
{
private:
  ....
  friend ::nlohmann::detail::parser<basic_json>;
  friend ::nlohmann::detail::serializer<basic_json>;
...
</basic_json></basic_json></typename,></typename></typename,></typename,>----

该库采用了一种“大而全”的做法。它包含丰富的功能，甚至包括那些小众用途的功能。其弱点在于，尽管许多模板参数允许配置，但它们阻碍了最佳优化。其后果是库的性能较差。配置值类型每个方面的能力产生了自相矛盾的效果，使其不太适合作为通用类型。

* {icon_bad} `basic_json` 是一个类模板。库必须在模板参数的选择上达成一致才能互操作。

* {icon_bad} 过度定制化。我们很难想象将 `BooleanType` 设置为 `bool` 之外的类型有何用例。

* {icon_bad} 关注点分离不佳。`basic_json` 容器声明不必要地将解析和序列化API混为一谈。

* {icon_bad} 分配器支持有限。只允许无状态分配器，这排除了最重要的一类分配器，即基于本地内存池的实现。

* {icon_bad} 没有增量式解析，也没有增量式序列化。

* {icon_bad} 解析和序列化性能差。

* {icon_good} 功能齐全，包括JSON Pointer、CBOR等。

== 与RapidJSON的比较

值类型：https://github.com/Tencent/rapidjson/blob/bb5f966b9939d6cdfbac3462a0410e185099b3af/include/rapidjson/document.h#L608[`rapidjson::GenericValue`]

[source]
----
template <typename encoding,="" typename="" allocator="MemoryPoolAllocator<"> &gt;
class GenericValue;
</typename>
template <bool const,="" typename="" valuet="">
class GenericArray;
</bool>
template <bool const,="" typename="" valuet="">
class GenericObject;
</bool>----

* {icon_bad} 值类型不是规整的。赋值具有破坏性，执行 `a = b` 等同于 `a = std::move(b)`。不允许拷贝构造和拷贝赋值。

* {icon_bad} 对象类型没有哈希表或索引来降低查找成本。

* {icon_bad} 分配器具有引用语义。很容易遇到生命周期问题。

* {icon_bad} 数组和对象类型的接口与标准库中的对应类型大不相同，且不符合惯用法。

* {icon_bad} 没有增量式解析，也没有增量式序列化。

* {icon_good} 解析和序列化性能优于大多数其他库。

=== 与SIMD JSON的比较

[source]
----
class ParsedJson;
----

这是一个非常有趣的数据结构，它经过优化以与SIMD解析器良好配合。它为目标用例做出了非常好的设计选择。然而，由于必要的限制，它不太适合作为通用类型。

* {icon_bad} 仅支持通过 `ParsedJson::BasicIterator` 进行顺序访问

* {icon_bad} 只读，只能由提供的SIMD JSON解析器填充。

* {icon_good} 目前最快的JSON解析器。
