[[header]]
== Background

[#author .author]#The first version of allocators in C{plus}{plus}
defined the named requirement# +
[#revnumber]#version ++{++req++_++Allocator},# [#revdate]#and made each
standard container a class template#

[[content]]
[[preamble]]
parameterized on the allocator type. For example, here is the
declaration for ++{++std++_++vector}:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_1,indent=0]
----

The standard allocator is ++{++req++_++DefaultConstructible}. To support
stateful allocators, containers provide additional constructor overloads
taking an allocator instance parameter.

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_2,indent=0]
----

While the system works, it has some usability problems:

* The container must be a class template.
* Parameterizing the allocator on the element type is clumsy.
* The system of allocator traits, especially POCCA and POCMA, is
complicated and error-prone.

Allocator-based programs which use multiple allocator types incur a
greater number of function template instantiations and are generally
slower to compile because class template function definitions must be
visible at all call sites.

[[_polymorphic_allocators]]
=== Polymorphic Allocators

C{plus}{plus}17 improves the allocator model by representing the
low-level allocation operation with an abstract interface called
++{++ref++_++memory++_++resource}, which is not parameterized on the
element type, and has no traits:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_3,indent=0]
----

The class template ++{++ref++_++polymorphic++_++allocator} wraps a
++{++ref++_++memory++_++resource} pointer and meets the requirements of
++{++req++_++Allocator}, allowing it to be used where an allocator is
expected. The standard provides type aliases using the polymorphic
allocator for standard containers:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_4,indent=0]
----

A polymorphic allocator constructs with a pointer to a memory resource:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_5,indent=0]
----

The memory resource is passed by pointer; ownership is not transferred.
The caller is responsible for extending the lifetime of the memory
resource until the last container which is using it goes out of scope,
otherwise the behavior is undefined. Sometimes this is the correct
model, such as in this example which uses a monotonic resource
constructed from a local stack buffer:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_6,indent=0]
----

However, sometimes shared ownership is needed. Specifically, that the
lifetime extension of the memory resource should be automatic. For
example, if a library wants to return a container which owns an instance
of the library’s custom memory resource as shown below:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_7,indent=0]
----

This can be worked around by declaring the container to use a custom
allocator (perhaps using a
`std::shared++_++ptr++<++ std::pmr::memory++_++resource ++>++` as a data
member). This hinders library composition; every library now exports
unique, incompatible container types. A raw memory resource pointer is
also easy to misuse:

[source,highlight]
----
Unresolved directive in tmpj5jz56lr.adoc - include::../../../test/doc_background.cpp[tag=doc_background_8,indent=0]
----

Workarounds for this problem are worse than the problem itself. The
library could return a pair with the vector and
`std::unique++_++ptr++<++std::pmr::memory++_++resource++>++` which the
caller must manage. Or the library could change its function signatures
to accept a ++{++ref++_++memory++_++resource}`++*++` provided by the
caller, where the library also makes public the desired memory resources
(`my++_++resource` above).

[[_problem_statement]]
=== Problem Statement

We would like an allocator model using a single type `T` with the
following properties:

* `T` is not a class template
* `T` references a ++{++ref++_++memory++_++resource}
* `T` supports both reference semantics or shared ownership
* `T` interoperates with code already using `std::pmr`

Boost.JSON solves this problem by introducing a new smart pointer called
link:#ref_storage_ptr[++[++ref++_++storage++_++ptr++]++] which builds
upon C{plus}{plus}17’s memory allocation interfaces, accomplishing the
goals above. As a result, libraries which use this type compose more
easily and enjoy faster compilation, as member functions for containers
which use the type can be defined out-of-line.

[[footer]]
[[footer-text]]
Version ++{++req++_++Allocator} +
Last updated 2025-12-05 19:05:14 UTC
