[[header]]
== 背景

[#author .author]#C{plus}{plus}中分配器的第一个版本定义了具名要求# +
[#revnumber]#版本 ++{++req++_++Allocator},#
[#revdate]#并使每个标准容器成为类模板#

[[content]]
[[preamble]]
通过分配器类型进行参数化。例如，以下是 ++{++std++_++vector} 的声明：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_1,indent=0]
----

标准分配器是++{++req++_++DefaultConstructible}。为支持有状态分配器，容器提供了额外的构造函数重载，这些重载接受一个分配器实例参数。

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_2,indent=0]
----

尽管该系统有效，但它存在一些可用性问题：

* 容器必须是类模板。
* 在元素类型上对分配器进行参数化是笨拙的。
* 分配器特征系统，特别是 POCCA 和 POCMA，既复杂又容易出错。

使用多种分配器类型的基于分配器的程序会产生更多的函数模板实例化，并且通常编译速度较慢，因为类模板的函数定义必须在所有调用点可见。

[[_polymorphic_allocators]]
=== 多态分配器

C{plus}{plus}17 通过使用名为 ++{++ref++_++memory++_++resource}
的抽象接口表示低级分配操作来改进分配器模型，该接口未在元素类型上参数化，且没有特征：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_3,indent=0]
----

类模板 ++{++ref++_++polymorphic++_++allocator} 封装了一个
++{++ref++_++memory++_++resource} 指针，并满足 ++{++req++_++Allocator}
的要求，使其可在需要分配器的地方使用。标准库为使用多态分配器的标准容器提供了类型别名：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_4,indent=0]
----

多态分配器通过指向内存资源的指针进行构造：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_5,indent=0]
----

内存资源通过指针传递；所有权不被转移。调用方负责延长内存资源的生命周期，直到使用它的最后一个容器超出作用域，否则行为未定义。有时这是正确的模型，例如在此示例中，该示例使用从本地栈缓冲区构造的单调资源：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_6,indent=0]
----

然而，有时需要共享所有权。具体而言，内存资源的生命周期延长应是自动的。例如，如果某个库希望返回一个容器，该容器拥有该库自定义内存资源的实例，如下所示：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_7,indent=0]
----

这可以通过声明容器使用自定义分配器（可能使用
`std::shared++_++ptr++<++ std::pmr::memory++_++resource ++>++`
作为数据成员）来解决。这阻碍了库的组合；每个库现在都导出独特且不兼容的容器类型。原始内存资源指针也容易被误用：

[source,highlight]
----
Unresolved directive in tmpp48t14mb.adoc - include::../../../test/doc_background.cpp[tag=doc_background_8,indent=0]
----

此问题的解决方法比问题本身更糟糕。该库可以返回一个包含 vector 和
`std::unique++_++ptr++<++std::pmr::memory++_++resource++>++` 的
pair，调用方必须管理它。或者，该库可以更改其函数签名以接受调用方提供的
++{++ref++_++memory++_++resource}`++*++`，同时该库还公开所需的内存资源（如上文的
`my++_++resource`）。

[[_problem_statement]]
=== 问题陈述

我们希望使用单一类型 `T` 的分配器模型，该模型具有以下属性：

* `T` 不是类模板
* `T` 引用一个 ++{++ref++_++memory++_++resource}
* `T` 支持引用语义或共享所有权
* `T` 与已使用 `std::pmr` 的代码互操作

Boost.JSON 通过引入一种称为
link:#ref_storage_ptr[++[++ref++_++storage++_++ptr++]++]
的新型智能指针来解决此问题，该指针基于 C{plus}{plus}17
的内存分配接口构建，实现了上述目标。因此，使用此类型的库更易于组合，并享有更快的编译速度，因为使用该类型的容器的成员函数可以外联定义。

[[footer]]
[[footer-text]]
版本 ++{++req++_++Allocator} +
最后更新于 2025-12-05 19:05:02 UTC
