////
Copyright (c) 2019 Vinnie Falco (vinnie.falco@gmail.com)
Copyright (c) 2025 Dmitry Arkhipov (grisumbras@yandex.ru)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/json
////

= 背景
C++中分配器的第一个版本定义了名为{req_Allocator}的要求，并使每个标准容器成为基于分配器类型的类模板。例如，以下是{std_vector}的声明：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_1,indent=0]
----

标准分配器是{req_DefaultConstructible}。为支持有状态分配器，容器提供了额外的构造函数重载，接受分配器实例参数。

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_2,indent=0]
----

虽然该系统可行，但存在一些可用性问题：

* 容器必须是类模板。
* 在元素类型上参数化分配器的方式笨拙。
* 分配器特征系统（特别是POCCA和POCMA）复杂且易出错。

使用多种分配器类型的基于分配器的程序会产生更多的函数模板实例化，并且通常编译速度较慢，因为类模板的函数定义在所有调用点都必须可见。

== 多态分配器

{cpp}17通过使用名为{ref_memory_resource}的抽象接口表示低级分配操作，改进了分配器模型。该接口未在元素类型上参数化，且无特征：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_3,indent=0]
----

类模板{ref_polymorphic_allocator}包装了{ref_memory_resource}指针，并满足{req_Allocator}要求，使其可在需要分配器的地方使用。标准库为使用多态分配器的标准容器提供了类型别名：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_4,indent=0]
----

多态分配器通过指向内存资源的指针构造：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_5,indent=0]
----

内存资源通过指针传递；所有权不发生转移。调用方需负责延长内存资源的生命周期，直到最后一个使用它的容器超出作用域，否则行为未定义。有时这是正确的模型，例如在此使用本地栈缓冲区构建的单调资源示例中：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_6,indent=0]
----

然而，有时需要共享所有权。具体而言，内存资源的生命周期延长应是自动的。例如，若某库希望返回一个容器，该容器拥有该库自定义内存资源的实例，如下所示：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_7,indent=0]
----

可通过声明容器使用自定义分配器（可能使用`std::shared_ptr`作为数据成员）来解决此问题。这阻碍了库的组合；每个库现在都导出独特且不兼容的容器类型。原始内存资源指针也容易被误用：

[source]
----
include::../../../test/doc_background.cpp[tag=doc_background_8,indent=0]
----

此问题的变通方案比问题本身更糟糕。库可返回一个包含vector和`std::unique_ptr<std::pmr::memory_resource>`的pair，调用方必须自行管理。或者库可更改其函数签名以接受调用方提供的{ref_memory_resource}``*``，同时库还需公开所需的内存资源（如上文的`my_resource`）。</std::pmr::memory_resource>

== 问题陈述

我们希望使用单一类型`T`的分配器模型，该模型具有以下属性：

* `T`不是类模板
* `T`引用{ref_memory_resource}
* `T`支持引用语义或共享所有权
* `T`与已使用`std::pmr`的代码互操作

Boost.JSON通过引入名为&lt;<ref_storage_ptr>&gt;的新型智能指针解决此问题，该指针基于{cpp}17的内存分配接口构建，实现了上述目标。因此，使用此类型的库更易于组合，并享有更快的编译速度，因为使用该类型的容器成员函数可被定义在外部。</ref_storage_ptr>
